version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
      - docker version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker build -t "Dockerfile"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.*
