version: 0.0
os: linux
files:
  - source: target/EmployeeApplication.jar
    destination: /home/ubuntu
permissions:
  - object: /scripts
    pattern: "*.sh"
    mode: 777
    type:
      - file     
hooks:
   AfterInstall:
     - location: /scripts/deployartifact.sh
       timeout: 3600
