version: 0.0
os: linux
files:
  - source: target/EmployeeApplication.jar
    destination: /home/ubuntu
  - source: scripts/deployartifact.sh
    destination: /home/ubuntu  
permissions:
  - object: /home/ubuntu
    pattern: "*.sh"
    mode: 777
    type:
      - file     
hooks:
   AfterInstall:
     - location: deployartifact.sh
       timeout: 3600
