version: 0.2

phases:
  pre_build:
    commands:
      - echo pre buils started on 'date'...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ems_java_docker_image:latest .   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push kdrnaik24/ems_java_docker_image:latest
